#!/bin/bash

clear

REPOSITORY=${1-"localhost:5000/jenkins"}
echo "Launching jenkins from $REPOSITORY"

docker run -p 8080:8080 -p 50000:50000 \
-v /var/jenkins_home:/var/jenkins_home \
-v /var/run/docker.sock:/var/run/docker.sock $REPOSITORY

